### ISSUE TITLE
Testing circle closing 

### ISSUE THREAD

**Issue by Sigillatus** [TheDwarfHorde/DHShapeMaker#1]
Tried this out just now & cannot fault it visually. The path xml doesn't appear to have Z appended. Should it?

I was surprised that a single circle generated 5 nubs. 

Two ellipses x start & finish nubs = 4. Plus a centre nub?? Why only one?

**Comment by technorobbo** [comment]
PathGeometry doesn't use Z it uses PathIsClosed
Each Arc has 4 parameters start end height width rotation

**Comment by Sigillatus** [comment]
Thanks for the explanation :)
